version: 2 # use CircleCI 2.0
jobs:
  build: # runs not using Workflows must have a `build` job as entry point
    docker:
      - image: circleci/node:10
    steps:
      - checkout # special step to check out source code to working directory
      - run:
          name: Update NPM
          command: 'sudo npm install -g npm@latest'
      - restore_cache: # special step to restore the dependency cache
          # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Build
          command: 'npm install && npm run build'
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Run tests
          command: 'npm run prettier:check && npm run test'
      - store_test_results:
          path: junit.xml
